### ISSUE TITLE
Documentation, Naming, and Packaging

### ISSUE THREAD

**Issue by noabarzohar1** [Ch3fUlrich/43513-01---Programming-for-Life-Sciences---4KP#12]
Naming and Packaging Issues:
- [x]  file names need to conform to Python conventions
- [x] code needs to be packaged (set.py or pyproject.toml)
- [x] good to support multiple installation options, but avoid keeping dependencies in two locations (requirements.dev, environment.yaml)
- [x] organise docstrings so that they conform to the most common conventions (google, dumpy, sphinx) - make sure this is consistent. example of google style:

Documentation Issues:
- [x]  consistently use type hints to improve readability/documentation practice
- [x] class, module and package level docstrings are missing - need to add at the beginning of files and for each class/module to explain their purpose
- [x] reduce inline comments (clean up) - can replace these comments with descriptive variables names or docstrings perhaps?

**Comment by Ch3fUlrich** [comment]
- [ ] A description for using setup.py, requirements_dev.txt is also needed
