### ISSUE TITLE
Critical Fail, negative molecule counts occur, some calculations are wrong in State.next_state()

### ISSUE THREAD

**Issue by Ch3fUlrich** [Ch3fUlrich/43513-01---Programming-for-Life-Sciences---4KP#8]
# Critical Fail
Critical Fail, negative molecule counts occur, some calculations are wrong in State.next_state()

Some runs create negative molecule counts, probably at the start of a simulation.

### Output
> Traceback (most recent call last):
>   File "/home/uniqueg/Work/biozentrum/pls-2024-group-b/Project/Gillespie_Simulation.py", line 789, in <module>
>     main()
>   File "/home/uniqueg/Work/biozentrum/pls-2024-group-b/Project/Gillespie_Simulation.py", line 780, in main
>     results = simulator.run(
>   File "/home/uniqueg/Work/biozentrum/pls-2024-group-b/Project/Gillespie_Simulation.py", line 110, in run
>     self.state.next_state(self.dt)
>   File "/home/uniqueg/Work/biozentrum/pls-2024-group-b/Project/Gillespie_Simulation.py", line 286, in next_state
>     miRNA_decayed = m["miRNA"].decay(dt)
>   File "/home/uniqueg/Work/biozentrum/pls-2024-group-b/Project/Gillespie_Simulation.py", line 514, in decay
>     return self.express(self.decay_rate, dt, from_count=self.count)
>   File "/home/uniqueg/Work/biozentrum/pls-2024-group-b/Project/Gillespie_Simulation.py", line 437, in express
>     count_diff = fast_random_occurrence(expression_rate, from_count)
> ValueError: negative dimensions not allowed

**Comment by kaydeno01** [comment]
I will have a look at this on the weekend if that's fine...
I will add a logger to pinpoint where negative counts might be introduced and try to fix it... 

The easiest would maybe be to just safeguard the counts to ever drop below 0?
something like:  m["miRNA"].count = max(0, m["miRNA"].count + miRNA_transcribed - miRNA_decayed)

**Comment by Ch3fUlrich** [comment]
Make Sure to pull from Main to have less conflicts in the end. You can Play around as you want
